/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


package views;
// importaciones 
// cerrar ventana 
import methods.cerrarVentana;

/**
 *
 * @author x4mv
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAreaDesarrollo = new javax.swing.JButton();
        btnBancoUsuario = new javax.swing.JButton();
        btnBancoPanel = new javax.swing.JButton();
        lblBancoEcosistema = new javax.swing.JLabel();
        lblBancoUsuario = new javax.swing.JLabel();
        lblAreaDesarrollo = new javax.swing.JLabel();
        lblBancoPanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");

        btnAreaDesarrollo.setText("Area Desarrollo");
        btnAreaDesarrollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaDesarrolloActionPerformed(evt);
            }
        });

        btnBancoUsuario.setText("Banker User");
        btnBancoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBancoUsuarioActionPerformed(evt);
            }
        });

        btnBancoPanel.setText("Banco Panel");
        btnBancoPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBancoPanelActionPerformed(evt);
            }
        });

        lblBancoEcosistema.setText("Bank-EcoSystem");
        lblBancoEcosistema.setToolTipText("");

        lblBancoUsuario.setText("Banking User");

        lblAreaDesarrollo.setText("Area Desarrollo");

        lblBancoPanel.setText("Banco Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAreaDesarrollo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBancoPanel)
                            .addComponent(lblBancoEcosistema, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBancoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 272, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBancoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBancoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAreaDesarrollo))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblBancoEcosistema)
                .addGap(27, 27, 27)
                .addComponent(lblBancoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBancoUsuario)
                .addGap(18, 18, 18)
                .addComponent(lblAreaDesarrollo)
                .addGap(18, 18, 18)
                .addComponent(btnAreaDesarrollo)
                .addGap(24, 24, 24)
                .addComponent(lblBancoPanel)
                .addGap(18, 18, 18)
                .addComponent(btnBancoPanel)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBancoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBancoUsuarioActionPerformed
        
        // Al hacer click en el btn de ingresar como Banco(cliente) aparece una ventana de inicio de sesion
        cerrarVentana.cerrar(this);
        InicioSesion view_inicioSesion = new InicioSesion();
        view_inicioSesion.setVisible(true);
        
        
    }//GEN-LAST:event_btnBancoUsuarioActionPerformed

    private void btnAreaDesarrolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaDesarrolloActionPerformed
        // TODO add your handling code here:
        
        // abrir el menu de inicio de sesio 
        cerrarVentana.cerrar(this);
        InicioSesion view_inicioSesion = new InicioSesion();
        view_inicioSesion.setVisible(true);
        
    }//GEN-LAST:event_btnAreaDesarrolloActionPerformed

    private void btnBancoPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBancoPanelActionPerformed
        // TODO add your handling code here:
        
        // abrir el menu de inicio de sesion
        cerrarVentana.cerrar(this);
        InicioSesion view_inicioSesion = new InicioSesion();
        view_inicioSesion.setVisible(true);
        
        // probando
    }//GEN-LAST:event_btnBancoPanelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAreaDesarrollo;
    private javax.swing.JButton btnBancoPanel;
    private javax.swing.JButton btnBancoUsuario;
    private javax.swing.JLabel lblAreaDesarrollo;
    private javax.swing.JLabel lblBancoEcosistema;
    private javax.swing.JLabel lblBancoPanel;
    private javax.swing.JLabel lblBancoUsuario;
    // End of variables declaration//GEN-END:variables
}
